# nixpacks.toml

providers = ["python"]

[phases.setup]
nixPkgs = ["tesseract"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
