services:
  - type: web
    name: flask-ocr-api
    env: python
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
